apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.service_name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: jhi-platform/${{ values.service_name }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - ${{ values.runtime }}
spec:
  type: service
  owner: ${{ values.owner }}
  system: ${{ values.system }}
  lifecycle: ${{ values.lifecycle }}
